version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh

      - run:
          name: Build service
          command: make

      - run:
          name: Build and push Docker image
          command: |
            docker build -t tigefa/dropbox .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push tigefa/dropbox
