version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git-all p7zip p7zip-full zip unzip
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            apt-get install -yqq nodejs python-pip python3-pip

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh

      - run:
          name: Build and push Docker image
          command: |
            docker build -t tigefa/dropbox .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push tigefa/dropbox
